openapi: 3.0.0
info:
  title: test
  version: "1.0"
  description: This is the one
servers:
  - url: https://api.server.test/v1
tags:
  - description: Tag description
    name: Update
paths:
  /test:
    get:
      tags:
        - Update
      operationId: get-test
      description: "Endpoint to get [Profile](./page/to/profile)"
      responses:
        "200":
          description: "Endpoint to get [Profile](./page/to/profile)"
          content:
            application/json:
              # RENDERS ALL VALUES IN THE SCHEMA
              # Comment this back in to render all of the spec
              # schema:
              #   $ref: "#/components/schemas/mainContentEntitySchema"

              # RENDERS ONLY THE strucutreEntity SCHEMA, not propertyKey1 + propertyKey2
              schema:
                type: object
                properties:
                  deeperContent:
                    $ref: "#/components/schemas/mainContentEntitySchema"
components:
  schemas:
    mainContentEntitySchema:
      allOf:
        - $ref: "#/components/schemas/structureEntity"
      properties:
        propertyKey1:
          $ref: "#/components/schemas/uid"
        propertyKey2:
          $ref: "#/components/schemas/status"
      required:
        - propertyKey1
        - propertyKey2
    structureEntity:
      properties:
        structureEntityKey1:
          description: The name
          type: string
        structureEntityKey2:
          description: The created at date
          format: date
          type: string
      required:
        - structureEntityKey1
        - structureEntityKey2
      title: Structure Entity
      type: object
    status:
      description: The status
      enum:
        - NEW
        - APPROVED
        - DECLINED
        - CANCELLED
      title: status
      type: string
    uid:
      example: cf67b798-6458-48f9-b1a6-dd240c0fc58b
      pattern: ^[a-fA-F0-9]{8}-(?:[a-fA-F0-9]{4}-){3}[a-fA-F0-9]{12}$|^@?(?:[A-Za-z0-9\-_]{4})*(?:[A-Za-z0-9\-_]{2}==|[A-Za-z0-9-_]{3}=)?$
      title: Unique Identifier (UID)
      type: string
